name: CI

on: [push, workflow_dispatch]
env:
  REPO: https://github.com/${{ github.repository }}

jobs:
  build:
    runs-on: self-hosted
    env:
      IMG_NAME: autocore/zenoh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        run: |
          docker buildx build \
          --output "type=image,push=true" \
          --platform linux/amd64,linux/arm64 \
          --build-arg REPO=${{ env.REPO }} \
          --tag ${{ env.IMG_NAME }}:$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g') \
          --file Dockerfile .